// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/CLI go through the direct (non-pooled) connection —
    // pooled/transaction-mode connections don't reliably support the
    // advisory locks Prisma Migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
